# Generated by Django 3.2.7 on 2021-12-16 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_sharepost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharepost',
            unique_together={('user', 'sharedUser')},
        ),
    ]
