# Generated by Django 3.2.7 on 2021-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sharepost_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepost',
            name='can_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='can_see',
            field=models.BooleanField(default=True),
        ),
    ]
