# Generated by Django 3.2.7 on 2021-12-18 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20211216_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharepost',
            unique_together={('user', 'sharedUser', 'file')},
        ),
    ]
